name: strlog
version: 2.0.0
license: MIT
description: >
  Structured, hierarchical, leveled logging for Dart.

  Features:
  - Built-in primitives for bound structured record context
  - Leveled records
  - Built-in configurable text and JSON log formatters
  - Built-in support for filtering records
  - Dozens of log record handlers out of the box

homepage: https://github.com/inoutgg/strlog.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.8
