name: jetlog
version: 2.0.0
license: MIT
description: >
  Compact and robust structured logger for Dart.

  This library provides a strongly typed APIs for logging records
  with structured data.

homepage: https://github.com/inoutgg/jetlog.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0
  macros: ^0.1.2-main.4

dev_dependencies:
  test: ^1.25.8
